[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/coupang-proxy"
  to = "http://34.134.96.117:3000/api/coupang-proxy"
  status = 200
  force = true

  [redirects.headers]
    X-From = "Netlify"
